version: "3.9"

services:
    api:
        build: .
        command: bash -c "yarn typeorm migration:run && yarn start"
        networks:
            - default
            - backend
        ports:
            - "3333:3333"

        depends_on:
            - db

    db:
        image: postgres
        environment: 
            POSTGRES_DB: 'gestao-cargas'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
        
        networks:
            - backend
        ports: 
            - "5432:5432"    

networks:
    default:
    backend:
        internal: True